project:
  type: website
  output-dir: _site
  render:
    - index.qmd

website:
  site-url: https://0minkoh.github.io/
  search: false
  page-navigation: false

lang: ko-KR

format:
  html:
    css: styles.css
    toc: false
    anchor-sections: false
